add govulncheck parser
DenisSlack/django-DefectDojo pull request #1
Opened 2022-11-29 08:34 UTC by DenisSlack

2022-11-29 10:19 UTC, REGIORGIOO requested changes

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +class govulncheckParser:
имя класса должно быть в PascalCase

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +        return "Import Govulncheck Scanner findings in JSON format."
все методы могут быть static, так как self нигде не используется

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +    def get_description_for_scan_types(self, scan_type):
scan_type не используется

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +        return "Import Govulncheck Scanner findings in JSON format."
и необходимость get_scan_types и get_label_for_scan_types не очень понимаю
первый, если он нужен где-то дальше, можно заменить на какую-нибудь константу
второй же просто возвращает то, что и принимает. Зачем нужен метод?

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +            date = date[0:10]
по идее, дальше дата нигде не используется

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +            location = call['CallSites'][0]['Pos']['Filename'] + ':' + str(call['CallSites'][0]['Pos']['Line']) + ':' \
лучше использовать f строки для интерполяции

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +            cve = descrip_vuln['aliases'][0]
я бы не вычленял первый элемент листа, а добавить все элементы(если будут случаи с len()>1) через метод extend

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +            for i in descrip_vuln['references']:
можно короче через list comprehension refs = [ref['url'] for ref in descrip_vuln['references']]

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +                    new_location = call['CallSites'][0]['Pos']['Filename'] + ':' + str(
см. коммент выше

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +            references = '\n'.join(str(i) for i in refs)
по идее в refs и так лежат строки, не уверен в необходимости str(). поэтому можно просто '\n'.join(refs)

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +                    new_location = call['CallSites'][0]['Pos']['Filename'] + ':' + str(
про f строку

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +            impact = 'Vulnerable method: ' + ", ".join(str(i) for i in impact)
аналогично предыдущему + f строка

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +            impact = impact + "\nVulnerable endpoints: \n" + '\n'.join(str(i) for i in vuln_files)
можно добавить в предыдущую строчку по аналогии

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +            refs = []
если дальше сделать через list comprehension, то здесь объявлять не нужно

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +            findings.append(finding)
можно сразу добавлять в список Finding(...)

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +        pos_json = scan_data.find(b'{')
не уверен в необходимости b

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +        return findings
в конце файла нужна пустая строчка по кодстайлу

2022-11-29 10:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +        scan_data = scan_data[pos_json:]
я бы объедини 22-23

2022-11-29 10:31 UTC, DenisSlack commented on dojo/tools/govulncheck/parser.py
> +    def get_description_for_scan_types(self, scan_type):
Дока Defect Dojo просит так
https://defectdojo.github.io/django-DefectDojo/contributing/how-to-write-a-parser/

2022-11-29 10:31 UTC, DenisSlack commented on dojo/tools/govulncheck/parser.py
> +        return "Import Govulncheck Scanner findings in JSON format."
Дока Defect Dojo просит так
https://defectdojo.github.io/django-DefectDojo/contributing/how-to-write-a-parser/

2022-11-29 10:31 UTC, DenisSlack commented on dojo/tools/govulncheck/parser.py
> +    def get_findings(self, scan_file, test):
Дока Defect Dojo просит так
https://defectdojo.github.io/django-DefectDojo/contributing/how-to-write-a-parser/

2022-11-29 10:32 UTC, DenisSlack commented on dojo/tools/govulncheck/parser.py
> +        pos_json = scan_data.find(b'{')
Пробовал без нее find - не работает

2022-11-29 18:19 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +            if vuln['OSV']['aliases'] in ignore:
я бы заменил на not inи убрал continue

2022-11-30 16:20 UTC, REGIORGIOO requested changes

2022-11-30 16:20 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +        location = f"{call['CallSites'][0]['Pos']['Filename']}:{str(call['CallSites'][0]['Pos']['Line'])}:" \
str() не нужны

2022-11-30 16:20 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +            references = str()
нет необходимости объявлять здесь строки

2022-11-30 16:20 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +            references = str()
я бы вынес из цикла все общее для всех элементов группы(типа title, description и тд) и убрал collected. эти значения можно достать из первого элемента группы, например
внутри цикла только добавления в два множетсва

2022-11-30 16:20 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +        location = f"{call['CallSites'][0]['Pos']['Filename']}:{str(call['CallSites'][0]['Pos']['Line'])}:" \
и еще я бы создал новую переменную data['Calls']['Functions'][str(node)]['CallSites'][0]['Pos'] вместо самого call, чтобы трижды не прописывать этот путь

2022-11-30 16:20 UTC, REGIORGIOO commented on dojo/tools/govulncheck/parser.py
> +        location = f"{call['CallSites'][0]['Pos']['Filename']}:{str(call['CallSites'][0]['Pos']['Line'])}:" \
и этот метод точно мб статиком 
+ можно возвращать cразу ф строку, без создания переменной location

2022-12-05 15:45 UTC, closed without merging